name: Rollback Acumatica Customization

on:
  workflow_dispatch:
    inputs:
      versionName:
        description: 'Customization package Name (e.g., SimpleCustomization1.1)'
        required: true
      targetEnv:
        description: 'Environment to rollback to (dev, qa, stage, prod)'
        required: true
        default: 'qa'

jobs:
  rollback:
    runs-on: self-hosted

    env:
      VERSION_NAME: ${{ github.event.inputs.versionName }}
      TARGET_ENV: ${{ github.event.inputs.targetEnv }}

    steps:
      - name: Download Artifact from Previous Version
        uses: actions/download-artifact@v4
        with:
          name: acumatica-customization
          path: rollback-package

      - name: List Files to Verify Download
        run: |
          echo "Downloaded rollback package contents:"
          ls -R rollback-package

      - name: Set Environment-Specific Secrets
        id: set-secrets
        run: |
          if ("${{ env.TARGET_ENV }}" -eq "dev") {
            echo "ACUMATICA_URL=${{ secrets.ACUMATICA_DEV_URL }}" >> $env:GITHUB_ENV
            echo "ACUMATICA_USERNAME=${{ secrets.ACUMATICA_DEV_USERNAME }}" >> $env:GITHUB_ENV
            echo "ACUMATICA_PASSWORD=${{ secrets.ACUMATICA_DEV_PASSWORD }}" >> $env:GITHUB_ENV
          }
          elseif ("${{ env.TARGET_ENV }}" -eq "qa") {
            echo "ACUMATICA_URL=${{ secrets.ACUMATICA_QA_URL }}" >> $env:GITHUB_ENV
            echo "ACUMATICA_USERNAME=${{ secrets.ACUMATICA_QA_USERNAME }}" >> $env:GITHUB_ENV
            echo "ACUMATICA_PASSWORD=${{ secrets.ACUMATICA_QA_PASSWORD }}" >> $env:GITHUB_ENV
          }
          # elseif ("${{ env.TARGET_ENV }}" -eq "stage") {
          #   echo "ACUMATICA_URL=${{ secrets.STAGE_URL }}" >> $env:GITHUB_ENV
          #   echo "ACUMATICA_USERNAME=${{ secrets.STAGE_USERNAME }}" >> $env:GITHUB_ENV
          #   echo "ACUMATICA_PASSWORD=${{ secrets.STAGE_PASSWORD }}" >> $env:GITHUB_ENV
          # }
          # elseif ("${{ env.TARGET_ENV }}" -eq "prod") {
          #   echo "ACUMATICA_URL=${{ secrets.PROD_URL }}" >> $env:GITHUB_ENV
          #   echo "ACUMATICA_USERNAME=${{ secrets.PROD_USERNAME }}" >> $env:GITHUB_ENV
          #   echo "ACUMATICA_PASSWORD=${{ secrets.PROD_PASSWORD }}" >> $env:GITHUB_ENV
          # }
          else {
            Write-Error "Unsupported environment: ${{ env.TARGET_ENV }}"
            exit 1
          }
        shell: pwsh

      - name: Rollback to ${{ env.VERSION_NAME }} on ${{ env.TARGET_ENV }}
        shell: pwsh
        env:
          ACUMATICA_URL: ${{ env.ACUMATICA_URL }}
          ACUMATICA_USERNAME: ${{ env.ACUMATICA_USERNAME }}
          ACUMATICA_PASSWORD: ${{ env.ACUMATICA_PASSWORD }}
        run: |
          ./publishCustomization.ps1 "${{ env.VERSION_NAME }}"
